### PR TITLE
NEW Convert frontend assets to use silverstripe/webpack-config

### LINKED ISSUE #67: Show a date stamp somewhere for when report was last generated
## AC
* The report should have a visible date for when the report was last updated. 
* When the report is refreshed/updated (when the "Check for updates" button is clicked) the date stamp should be able to attract the users attention to the fact the report update is complete. eg. Turns green or background has visible change. 
* The date stamp only need to be implemented for SS4 version of the module (excludes SS3)

## Tasks
* [x] Design to be provided by @sachajudd
* [x] Reassess and adjust effort required (story points) based on designs provided
* [x] Implementation for SS4 only
* [x] Time stamp is captured in the generated CSV file
* [x] Design review

## Notes
We (designers) are open to see what possibilities we have in regards to a loading state for the "Check for updates" button in the SS4 version—do we use the three dots loading indicator as per main actions in the Pages section or whether a spinning icon is easier to implement in this situation. Do some investigation and get back to us with whats possible before making a PR.

### LINKED ISSUE #79: Convert CSS and Javascript to use webpack config

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #79 

Also resolves #67

### CODE REVIEW

**Comment by robbieaverill** [comment]
@sachajudd I've added the changes to this pull request to show the last updated date on the report, for example:

image

I wasn't able to make the text green after updating the report because the reloading of the GridField is done with AJAX and we'd need to wait for that to complete before setting the text colour to green. The (legacy) GridField javascript API in core _does_ have a "success callback" for GridField's `reload()` function, but it gets executed before the GridField is reloaded so it's basically pointless.

I tried to add it to the initial report generation based on whether the report is rendered via AJAX, but clicking on the "Check for updates" also refreshes the report via AJAX when you first click on it (not ideal, but it is what it is for now).

Are you happy to leave out the green colour and shorter text?

**Comment by sachajudd** [comment]
Right, thanks for explaining. One of the AC's was to be able to attract the users attention so probably have to chat with @clarkepaul if we want to still achieve this.

**Comment by sachajudd** [comment]
@robbieaverill P.C missed a couple of things. Could you please remove the commas and rearrange the time to be 31 May rather than May 31. Cheers.

**Comment by robbieaverill** [comment]
Sweet, checked with @clarkepaul and we've logged the necessary improvements for the green text at #87

**Pull request merged**
